#!/bin/bash
set -e

echo "Best Practice Guide: Documentation Integration" >&2
echo "==============================================" >&2

# Check for required arguments
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: $0 <topic> <target-doc> [section]" >&2
    echo "Example: $0 'react-performance' AGENTS.md 'Best Practices'" >&2
    echo "Target docs: AGENTS.md, CLAUDE.md, README.md, docs/*.md" >&2
    exit 1
fi

TOPIC="$1"
TARGET_DOC="$2"
SECTION="${3:-Best Practices}"
TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S)

echo "Topic: $TOPIC" >&2
echo "Target document: $TARGET_DOC" >&2
echo "Section: $SECTION" >&2
echo "Timestamp: $TIMESTAMP" >&2
echo "" >&2

# Check if target document exists
if [ ! -f "$TARGET_DOC" ]; then
    echo "⚠️  Target document not found: $TARGET_DOC" >&2
    echo "Creating new document..." >&2
    touch "$TARGET_DOC"
fi

# Check for existing guide references
SKILL_DIR="skills/${TOPIC}-guide"
DOC_FILE="docs/${TOPIC}-guide.md"

# Determine what guides exist
GUIDE_TYPES=()
if [ -d "$SKILL_DIR" ]; then
    GUIDE_TYPES+=("skill")
    echo "✅ Found skill guide: $SKILL_DIR" >&2
fi

if [ -f "$DOC_FILE" ]; then
    GUIDE_TYPES+=("documentation")
    echo "✅ Found documentation guide: $DOC_FILE" >&2
fi

if [ ${#GUIDE_TYPES[@]} -eq 0 ]; then
    echo "❌ No guides found for topic: $TOPIC" >&2
    echo "Run generate-guide.sh first to create guides." >&2
    exit 1
fi

echo "" >&2
echo "Analyzing target document structure..." >&2

# Check if section exists
if grep -q "## $SECTION" "$TARGET_DOC"; then
    echo "✅ Section found: ## $SECTION" >&2
    SECTION_EXISTS=true
else
    echo "⚠️  Section not found: ## $SECTION" >&2
    echo "Will add section at end of document." >&2
    SECTION_EXISTS=false
fi

# Check for existing topic reference
if grep -iq "$TOPIC" "$TARGET_DOC"; then
    echo "⚠️  Topic already referenced in document" >&2
    EXISTING_REFERENCE=true
else
    EXISTING_REFERENCE=false
fi

echo "" >&2
echo "Gener integration content..." >&2

# Create integration content
INTEGRATION_CONTENT=""

case ${#GUIDE_TYPES[@]} in
    1)
        # Single guide type
        if [ "${GUIDE_TYPES[0]}" = "skill" ]; then
            INTEGRATION_CONTENT="### ${TOPIC^} Best Practices\n\nSee \`$SKILL_DIR/\` for comprehensive ${TOPIC} best practices, implementation patterns, and validation tools.\n\n*Generated by best-practice-guide skill - $TIMESTAMP*"
        else
            INTEGRATION_CONTENT="### ${TOPIC^} Best Practices\n\nSee \`$DOC_FILE\` for detailed ${TOPIC} guidelines covering security, performance, and implementation considerations.\n\n*Generated by best-practice-guide skill - $TIMESTAMP*"
        fi
        ;;
    2)
        # Both skill and documentation
        INTEGRATION_CONTENT="### ${TOPIC^} Best Practices\n\n- **Quick reference & tools**: \`$SKILL_DIR/\` (agent-discoverable skill)\n- **Detailed guidelines**: \`$DOC_FILE\` (comprehensive documentation)\n\n*Generated by best-practice-guide skill - $TIMESTAMP*"
        ;;
esac

echo "Integration content:" >&2
echo "-------------------" >&2
echo -e "$INTEGRATION_CONTENT" >&2
echo "" >&2

# Backup original document
BACKUP_FILE="${TARGET_DOC}.backup-$(date +%Y%m%d-%H%M%S)"
cp "$TARGET_DOC" "$BACKUP_FILE"
echo "✅ Created backup: $BACKUP_FILE" >&2

echo "Updating document..." >&2

if [ "$SECTION_EXISTS" = true ]; then
    # Section exists, add to it
    # Find the section and add content after it
    SECTION_LINE=$(grep -n "## $SECTION" "$TARGET_DOC" | head -1 | cut -d: -f1)
    
    if [ -n "$SECTION_LINE" ]; then
        # Find the next section or end of file
        TOTAL_LINES=$(wc -l < "$TARGET_DOC")
        NEXT_SECTION_LINE=$TOTAL_LINES
        
        for ((i=SECTION_LINE+1; i<=TOTAL_LINES; i++)); do
            LINE=$(sed -n "${i}p" "$TARGET_DOC")
            if [[ "$LINE" =~ ^##[[:space:]] ]]; then
                NEXT_SECTION_LINE=$((i-1))
                break
            fi
        done
        
        # Insert content before next section
        {
            head -n "$NEXT_SECTION_LINE" "$TARGET_DOC"
            echo ""
            echo -e "$INTEGRATION_CONTENT"
            tail -n +$((NEXT_SECTION_LINE+1)) "$TARGET_DOC"
        } > "${TARGET_DOC}.tmp"
        
        mv "${TARGET_DOC}.tmp" "$TARGET_DOC"
        echo "✅ Added to existing section: ## $SECTION" >&2
    else
        echo "❌ Could not find section line" >&2
        exit 1
    fi
else
    # Section doesn't exist, add at end
    echo "" >> "$TARGET_DOC"
    echo "## $SECTION" >> "$TARGET_DOC"
    echo "" >> "$TARGET_DOC"
    echo -e "$INTEGRATION_CONTENT" >> "$TARGET_DOC"
    echo "✅ Added new section: ## $SECTION" >&2
fi

echo "" >&2
echo "Verifying update..." >&2

# Check if update was successful
if grep -q "$TOPIC" "$TARGET_DOC"; then
    echo "✅ Topic successfully integrated into $TARGET_DOC" >&2
else
    echo "❌ Integration may have failed" >&2
    echo "Check $TARGET_DOC manually" >&2
fi

echo "" >&2
echo "Integration complete!" >&2
echo "" >&2

# Show the updated section
echo "Updated section preview:" >&2
echo "-----------------------" >&2
grep -A 10 -B 2 "## $SECTION" "$TARGET_DOC" | head -20 >&2

echo "" >&2
echo "Additional integration recommendations:" >&2
echo "--------------------------------------" >&2

# Additional integration suggestions
case "$TARGET_DOC" in
    "AGENTS.md")
        echo "1. Consider adding to skill reference table if present" >&2
        echo "2. Update skill count in document header if present" >&2
        echo "3. Link from related skill descriptions" >&2
        ;;
    "CLAUDE.md")
        echo "1. Consider context-specific examples for Claude" >&2
        echo "2. Add prompt engineering tips if relevant" >&2
        echo "3. Link from tool usage sections" >&2
        ;;
    "README.md")
        echo "1. Consider adding to table of contents if present" >&2
        echo "2. Link from getting started or development sections" >&2
        echo "3. Update project overview if relevant" >&2
        ;;
esac

echo "" >&2
echo "Next steps:" >&2
echo "1. Review the integrated content" >&2
echo "2. Customize for project-specific needs" >&2
echo "3. Test links and references" >&2
echo "4. Consider cross-references from other documentation" >&2

echo '{"status": "integrated", "topic": "'"$TOPIC"'", "target_document": "'"$TARGET_DOC"'", "section": "'"$SECTION"'", "guide_types": ['$(IFS=,; echo "${GUIDE_TYPES[*]}")'], "timestamp": "'"$TIMESTAMP"'", "backup_file": "'"$BACKUP_FILE"'"}'